name: Build and Push Docker Image (Windows)

on:
  push:
    branches:
      - main  # Replace with your target branch name if different

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Add this step to set up Buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image (Windows)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.windows  # Specify Windows Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/testdocker:latest-windows
          platforms: windows/amd64
